# IDEAS DE PROYECTO:

### 1) Realizar análisis de precio-umbral para mínimo 4 acciones (de preferencia del mismo rubro) 

### 2) Solucionar por medio de la aproximación montecarlo algún problema físico que se modele con integrales múltiples (dobles, triples, etc) 

### 3) Cualquier problema de probabilidad, analizarlo por medio de simulación montecarlo. (Casino y apostador)

### 4) Problema Monty Hall (ver enlaces para explicación del problema)
 > - https://en.wikipedia.org/wiki/Monty_Hall_problem
 > - https://www.youtube.com/watch?v=1BpTBzDQuRE
 
### 5) Generación de terrenos aleatorios mediante ruido (fractales)

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/b/b6/Proyecto_en_construccion.jpg" width="300px" height="100px" />


# Guía para presentación de proyectos.
> Se especifican los componentes básicos que deberá tener cada proyecto. El proyecto debe ser un problema que se pueda modelar con las herramientas vistas en el módulo. En el caso del segundo módulo, simulación montecarlo.

___
## 1. Entregable.
Los trabajos deben tener los siguientes componentes básicos.

### 1.1 Título del trabajo.
> Debe describir el trabajo.

### 1.2 Introducción
> Debe contextualizar y describir el problema que se va a trabajar.


### 1.3 Objetivos.
> - Se refieren a los propósitos por los cuales se hace el trabajo.
> - Deben ser concretos, evaluables y verificables.
> - Deben ser escritos en infinitivo.
> #### 1.1 Objetivo general.
>  - Fin último de estudio. Se formula atendiendo el propósito global del trabajo. No presenta detalles.
>  - Se orienta a la totalidad del trabajo. Tiene que ver con el título del trabajo.
> #### 1.2 Objetivos específicos
>  - De forma detallada describen cada una de los componentes del trabajo.
>  - En conjunto garantizan la consecución del objetivo general.

Referencia:
- https://es.slideshare.net/rosbur/metodologia-objetivos-generales-y-especficos

### 1.4 Modelo que representa el problema.
> - Se debe incluir las ecuaciones que rigen el sistema que se está estudiando.
> - Deducción del modelo. Explicación detallada de las ecuaciones de acuerdo al problema que se quiera resolver o modelo que se quiera representar.
> - ¿Qué situación representa el modelo? ¿Cuáles son las limitaciones fundamentales?
> - Significado y valor de los parámetros (constantes que aparezcan en el modelo).

### 1.5 Solución del problema.
> - Se debe resolver el problema.
> - ¿Condujo el algoritmo a una solución factible?

### 1.6 Visualización de la solución del problema.
> Se deben mostrar gráficas y/o tablas que ilustren de forma adecuada los resultados. No olviden etiquetar los ejes y si se tienen varias curvas en una sola gráfica también etiquetarlas (ojo: que las curvas se puedan diferenciar con colores y estilos de línea).

### 1.7 Conclusiones.
> Mucho cuidado, las conclusiones no son cualquier cosa. Se debe concluir respecto a los objetivos planteados de acuerdo a los resultados obtenidos.

### 1.8 Referencias.
> Citar (en formato APA) la bibliografía utilizada.

___
## 2. Especificaciones adicionales.
En el grupo deben haber mínimo dos integrantes y máximo tres integrantes. Para propósitos logísticos nada más, por favor enumérense como *integrante 1*, *integrante 2* e *integrante 3*.

### 2.1 Notebook de jupyter. 
> Los anteriores numerales los deben desarrollar todos en un notebook de jupyter y llamarlo de la siguiente manera `PM2_ApellidoN1_ApellidoN2_ApellidoN3`, donde `ApellidoNi` hace referencia al apellido paterno y la inicial del primer nombre del integrante `i`.

### 2.2 Presentación.
> Recuerden que la nota del proyecto es mitad el trabajo, y mitad la presentación. Deben hacer una presentación en power point para presentar el trabajo en la clase del **Lunes 31 de Octubre de 2022.** La presentación, además de llevar todos los componentes básicos descritos en el entregable, debe llevar una tabla de contenido.
> - **NO DEBE TENER CÓDIGO, PARA ESO ES EL INFORME EN EL NOTEBOOK**
> - Presentación: **MÁXIMO** 10 minutos. Se interrumpirá la presentación del equipo a los 10 minutos.
> - Seguir estas recomendaciones: https://es.slideshare.net/MeireComputacion/power-point-pautas-para-una-buen-trabajo

In [50]:
import numpy as np
import pandas as pd
import random

In [51]:
matriz = np.array([[0,0,0],
                   [0,0,0],
                   [0,0,0]])
matriz

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
mborde = np.pad(matriz,pad_width=1,mode="constant",constant_values=0)
mborde

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [53]:
n = len(mborde)
n

5

In [54]:
m2 = np.zeros((2*n-3,2*n-3))
m2

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [55]:
n2 = len(m2)

for i in range (1, n2-3):
    for j in range (1, n2-3):
        m2[2*i-1,2*j-1]=mborde[i,j]
        #print(m2[i,j])
        #print(2*i-1,2*j-1)

In [67]:
mcuadrados = m2
rango = 1

for i in range (1,4):
    for j in range (2,n2-2,2):
        mcuadrados[i,j] = (mcuadrados[i-1,j-1]+mcuadrados[i+1,j+1]+mcuadrados[i+1,j-1]+mcuadrados[i-1,j+1])*0.25 + 2*rango*random.choices([0.2,0.5,0.8],weights=[3,5,2],k=1)

TypeError: 'int' object is not callable